services:
  moontv-core:
    image: ghcr.io/tom2almighty/lunatv:latest
    container_name: moontv-core
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      - VITE_ADMIN_PASSWORD=your_password
      # - VITE_CONFIG_SUBSCRIPTION_URL=https://example.com/subscribe
      # - VITE_SITE_NAME=VODHUB
