services:
  moontv-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moontv-core
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      - APP_ADMIN_USERNAME=admin
      - APP_ADMIN_PASSWORD=your_password
      - CRON_SECRET=strong_secret
    volumes:
      - ./data:/app/data
